name: DiscordStuff
version: '${version}'
main: me.comfortable_andy.discordstuff.DiscordStuffMain
api-version: 1.16
authors: [ Comfortable_Andy ]
permissions:
  discordstuff.commands.*:
    description: Allows the user to use all message commands under this plugin
    default: true
  discordstuff.commands.plugin:
    description: Allows the user to use the plugin command
    default: op
    children:
      - discordstuff.commands.plugin.reload
      - discordstuff.commands.plugin.test
      - discordstuff.commands.plugin.parser
  discordstuff.commands.plugin.reload:
    description: Allows the user to reload the plugin
    default: op
  discordstuff.commands.plugin.test:
    description: Allows the user to test the markdown
    default: op
  discordstuff.commands.plugin.parser:
    description: Allows the user to modify the markdown parser
    default: op
  discordstuff.commands.plugin.emoji:
    description: Allows the user to access emoji commands (re-download)
  discordstuff.ping.use:
    description: Allows pinging other players
    default: true

commands:
  discordstuff:
    description: Plugin command for DiscordStuff
    permission: discordstuff.commands.plugin
    aliases:
      - stuff
      - ds